name: 'push-PR-blocker'
description: 'This repository will block the unwanted push and pull requests to the production deployed branches'
author: 'Vishvajeet Singh'
inputs:
  BRANCH_NAME:
    required: true
    description: "the name of the current branch"
  ENVIRONMENT_NAME:
    required: true
    description: "the name of the environment variable"
  BUCKET_NAME:
    required: true
    description: 'AWS S3 bucket to push the data'
  SERVICE_NAME:
    required: true
    description: 'Name of the service using this action'
  REGION:
    required: true
    description: 'AWS S3 bucket region'
  TARGET_BRANCH:
    required: true
    description: 'Target branch of PR'
  
runs:
  using: 'node16'
  main: 'dist/index.js'
